// Datos del Tema 1 (Números enteros) · Adaptaciones PTE · 2.º ESO
// Estructura: apartado → teoría + ejemplos + actividades (1 caja = 1 página).
// Los textos admiten **negrita**. Ln = [desde, hasta, marcas[x, etiqueta, color]].
// Colores de marca: rojo | azul | verde | violeta | ambar.

export type Ln = [number, number, [number, string, string][]];
export type Nv = { in?: string; p: string[]; s: string[]; ad?: string };
export type Act = { t: string; d: string; ic: string; ln?: Ln; regla?: boolean; nv: Nv[] };
export type Ap = { slug: string; n: number; t: string; teoria: string[]; ej: string[] };

export const CLS = [
  "border-violet-300 bg-violet-50 text-violet-700",
  "border-sky-300 bg-sky-50 text-sky-700",
  "border-emerald-300 bg-emerald-50 text-emerald-700",
  "border-amber-300 bg-amber-50 text-amber-700",
];
export const LABELS = [
  "2.º ESO · nivel de referencia",
  "1.º ESO · adaptación",
  "6.º primaria · adaptación",
  "5.º primaria · adaptación",
];

export const APS: Ap[] = [
  {
    slug: "01-introduccion", n: 1, t: "Introducción a los números enteros",
    teoria: [
      "Los números que usas para contar ($1, 2, 3, \\ldots$) y el $0$ forman los **números naturales**. Pero hay situaciones de la vida real que los naturales no pueden expresar: $-3\\,\\text{°C}$ en Morella a las 6 h, un descubierto de $-11\\,\\text{€}$ en el banco o el sótano $-2$ del parking del centro de salud. Para ellas existen los **números negativos**, que se escriben con un signo menos delante.",
      "Los negativos, el cero y los positivos juntos forman el conjunto de los **números enteros**, que se escribe $\\mathbb{Z}$. El $0$ no es ni positivo ni negativo: es la **frontera** entre los dos mundos y el único número sin signo.",
      "RAW:<table><caption>Los enteros en tu día a día</caption><thead><tr><th>Situación real</th><th>Número entero</th><th>Cómo se lee</th></tr></thead><tbody><tr><td>Neblina en Morella a las 6 h</td><td>$-3$ °C</td><td>«tres grados bajo cero»</td></tr><tr><td>Sótano 2 de un parking</td><td>$-2$</td><td>«menos dos»</td></tr><tr><td>Descubierto bancario</td><td>$-11$ €</td><td>«debe once euros»</td></tr><tr><td>Saldo a favor</td><td>$+45$ €</td><td>«cuarenta y cinco a favor»</td></tr><tr><td>Buzo a 18 m de profundidad</td><td>$-18$ m</td><td>«menos dieciocho, bajo el mar»</td></tr></tbody></table>",
      "La idea clave de todo el tema: el signo **no dice tamaño, dice dirección**. $+20$ y $-20$ están **igual de lejos del $0$** (eso lo mide el valor absoluto), pero uno sube, suma, está por encima… y el otro baja, resta, está por debajo. Fíjate: un termómetro tumbado no miente — $-20\\,\\text{°C}$ y $+20\\,\\text{°C}$ no son «el mismo frío».",
      "Cómo escribir tú un entero desde una situación real, en 3 pasos: 1) decide la **dirección** (¿bajo cero? ¿deber? ¿debajo?) → eso da el signo; 2) escribe la **cantidad** sin signo; 3) añade la **unidad** (°C, €, m). Así, «un buzo a 18 m bajo el mar» se escribe $-18\\ \\text{m}$.",
    ],
    ej: [
      "El lunes hace −3 °C y el martes +3 °C: **no** es el mismo día; uno está por debajo del cero y el otro por encima.",
      "Maria gasta 62 € teniendo 45 €: el banco anota **−11 €**, que significa «debe 11 €», no «tiene 11 €».",
      "En el parking, el sótano −2 está **más abajo** que el −1: cuanto más negativo, más profundo.",
    ],
  },
  {
    slug: "02-recta", n: 2, t: "La recta numérica",
    teoria: [
      "La **recta numérica** es una línea horizontal con el $0$ marcado y distancias iguales entre números consecutivos: cada paso a la derecha **suma** $1$; cada paso a la izquierda, **resta** $1$. Es la herramienta de todo el tema: cuando dudes de un signo, dibújala.",
      "Fig:termo",
      "En la recta los enteros son **posiciones**: $-6$ es el punto situado 6 pasos a la izquierda del $0$. Por eso la comparación es inmediata: **el que está más a la derecha siempre es mayor**, también entre negativos — $-1 > -6$ porque $-1$ está más cerca del $0$ por la derecha.",
      "Moverse por la recta es operar: empezar en un negativo no cambia la forma de andar. Desde $-3$, dar $+5$ pasos te lleva al $+2$ cruzando el cero de camino — ese cruce es justo lo que la recta te deja **ver** y el cálculo a ciegas esconde.",
      "Tres palabras que debes saber señalar en el dibujo: **origen** (el $0$), **unidad** (la distancia entre dos consecutivos, siempre la misma) y **valor absoluto** (cuántos pasos hay del número al origen, sin mirar la dirección: $|-6| = 6$).",
    ],
    ej: [
      "Situar −4: cuatro pasos a la izquierda del 0. Situar +2: dos a la derecha.",
      "Desde −3, subir 5: −3 → −2 → −1 → 0 → +1 → **+2**. El salto cruza el cero sin problemas.",
      "−6 es más frío que −1: en la recta del termómetro (horizontal), −6 queda más a la izquierda.",
    ],
  },
  {
    slug: "03-comparacion", n: 3, t: "Comparación de números enteros",
    teoria: [
      "Comparar enteros es responder «¿quién es mayor?». La regla de la recta lo resuelve todo: en horizontal, **más a la derecha = mayor**. De ahí salen los tres casos: positivo $>$ $0$ $>$ negativo; entre un positivo y un negativo ni lo dudes; y **entre dos negativos gana el que debe menos**: $-1 > -6$.",
      "El **valor absoluto** de un número, $|a|$, es su **distancia al $0$** sin mirar el signo: $|7| = 7$, $|-7| = 7$, $|0| = 0$. Dos números son **opuestos** si tienen igual valor absoluto y signos contrarios ($+5$ y $-5$): en la recta son simétricos respecto al $0$, y su suma siempre es $0$: $5 + (-5) = 0$.",
      "RAW:<table><caption>Los tres errores típicos al comparar (y su antídoto)</caption><thead><tr><th>Lo que parece</th><th>Lo que es</th><th>Antídoto</th></tr></thead><tbody><tr><td>«$-9$ es mayor que $-2$ porque $9>2$»</td><td>$-9 < -2$</td><td>Traduce a dinero: «debe 9 € vs debe 2 €» — está mejor quien debe menos.</td></tr><tr><td>«$|-6| = -6$»</td><td>$|-6| = 6$</td><td>Una distancia nunca es negativa.</td></tr><tr><td>«el $0$ es positivo»</td><td>El $0$ no tiene signo</td><td>Es la frontera: separa, no pertenece a ningún lado.</td></tr></tbody></table>",
      "Truco para el examen: «$-8 > -14$» se justifica diciendo «porque **debe menos**» o «porque está **más cerca del cero**». Saber justificar vale más que saber memorizar — y es lo que el tribunal escucha.",
    ],
    ej: [
      "−3 < 2: todo negativo es menor que todo positivo.",
      "−8 < −5: de los dos negativos, gana (es mayor) el que debe menos.",
      "|−7| = 7 y su opuesto es +7; pero −7 no es «menor que −7»: es el mismo número.",
    ],
  },
  {
    slug: "04-suma-resta", n: 4, t: "Suma y resta de enteros",
    teoria: [
      "Sumar y restar enteros es **andar por la recta**: $+a$ va a la derecha, $-a$ va a la izquierda. Desde donde estés: $-4 + 6 = 2$ (andas 6 a la derecha desde $-4$). Si el recorrido cruza el cero, la recta te lo enseña sin trampa.",
      "La regla en tres casos para no depender del dibujo. **Mismo signo** → sumas los valores y repites el signo: $(-7) + (-2) = -9$. **Signos distintos** → restas los valores y gana el signo del que más vale: $(-7) + 4 = -3$ porque $|-7| > |4|$. **Restar es sumar el opuesto**: $a - b = a + (-b)$, así que $5 - 8 = 5 + (-8) = -3$.",
      "Fig:signos",
      "El fallo más caro del examen: **restar un negativo**. Quitar deudas mejora: $-3 - (-9) = -3 + 9 = 6$. Regla de oro: cuando veas dos signos seguidos, $-(-\\,)\\;$ o $+(-\\,)$, **reescríbelo primero** como $+$ o $-$ sueltos y solo entonces calcula.",
      "Comprobación con diferencia de temperaturas, que sale siempre: de $-4$ °C a $9$ °C no suben $13$ °C «a ojo»: del $-4$ al $0$ hay $4$ y del $0$ al $9$ hay $9$, total $4+9=13$ °C. La resta $9-(-4)=13$ dice lo mismo — si la recta y el cálculo no coinciden, el error está en los signos.",
    ],
    ej: [
      "(−7) + 4 = −3 · 5 − 8 = −3 · (−3) − (−9) = −3 + 9 = 6.",
      "Saldo 45, gasto 62, ingreso 20: 45 − 62 + 20 = +3 → el saldo puede volver a positivo a mitad de semana.",
      "Diferencia de −4 °C a 9 °C: del −4 al 0 hay 4 y del 0 al 9 hay 9: 4 + 9 = **13 °C**.",
    ],
  },
  {
    slug: "05-combinadas", n: 5, t: "Operaciones combinadas",
    teoria: [
      "Con varias operaciones seguidas hace falta un **orden pactado**; si no, cada persona saca un resultado distinto. La jerarquía es siempre la misma:",
      "Fig:jerarquia",
      "Con enteros la lista no cambia; lo que cambia es que **cada término lleva su signo pegado**. El truco anti-fallo: reescribir la cadena como **suma algebraica** (toda resta convertida en «$+$ un negativo»), sumar luego los positivos por un lado y los negativos por el otro: $(-2) + 5 - 3 + 4 = (5+4) + (-2-3) = 9 - 5 = +4$.",
      "Los paréntesis **mandan y protegen**: $12 - (3 + 1) = 12 - 4 = 8$, pero si te los saltas sale $12-3+1 = 10$. Con un signo delante del paréntesis, repártelo: $8 - (-3 + 1) = 8 + 3 - 1 = 10$.",
      "La comprobación de cualquier recorrido (ascensor, temperatura, cuenta) es el **recorrido directo** en la recta: calcula aparte a cuántas plantas pensabas llegar; si el número no coincide con el punto de la recta, revisa el orden de los signos antes de responder.",
    ],
    ej: [
      "(−2) + 5 − 3 + 4 = (9 positivos) − (5 negativos) = **+4** · y el ascensor: −2 → +3 → 0 → +4.",
      "12 − (−3 + 8) → dentro del paréntesis primero: 5 → 12 − 5 = **7**.",
      "(−8) + 3 − (−5) + 1 = −8 + 3 + 5 + 1 = **+1**.",
    ],
  },
  {
    slug: "06-problemas", n: 6, t: "Problemas de la vida real",
    teoria: [
      "Resolver problemas con enteros es casi siempre **traducir** el enunciado a números con signo, calcular, y **devolver** el resultado en una frase con unidad. Las traducciones que salen en todos los exámenes:",
      "RAW:<table><caption>Traductor: enunciado → operación</caption><thead><tr><th>Si el problema dice…</th><th>Operación</th><th>Ojo con…</th></tr></thead><tbody><tr><td>«diferencia de temperatura entre $a$ y $b$»</td><td>$a - b$</td><td>Es una resta, no sumar los dos números sin más.</td></tr><tr><td>«sube $x$ y baja $y$»</td><td>$+x - y$ sobre el estado anterior</td><td>Se parte de donde se está, no del $0$.</td></tr><tr><td>«debe» / «descubierto»</td><td>saldo negativo</td><td>«Debe menos» = está mejor = número MAYOR.</td></tr><tr><td>«bajo el nivel del mar»</td><td>altitud negativa</td><td>El nivel del mar es el $0$ de la recta.</td></tr></tbody></table>",
      "Fig:fases",
      "El método de las 4 fases vale para cualquier problema del tema: **subraya** datos y pregunta → **dibuja** la recta o el esquema → **escribe la operación completa antes de calcular** (es el paso que más puntos salva: el tribunal valora el planteamiento) → **responde con frase y unidad**. Sin la fase 4, una calculadora también sabía el número.",
      "Y antes de dar la respuesta por buena, **comprobación de sentido**: ¿el signo dice lo que debía decir? Si un buzo «sube» y su número baja, hay un error de signo — no de cálculo.",
    ],
    ej: [
      "Dron a +45 m que baja 70 m: 45 − 70 = **−25 m** → 25 m por debajo del suelo del valle.",
      "De −6 °C a 2 °C: 2 − (−6) = **8 °C de subida** (no «6» ni «−4»).",
      "Dos cuentas en −8 € y −14 €: −8 − (−14) = 6 → la primera debe **6 € menos**: está mejor.",
    ],
  },
  {
    slug: "07-multiplicacion", n: 7, t: "Multiplicación y división de enteros",
    teoria: [
      "Multiplicar o dividir enteros se hace en **dos tiempos**: primero multiplicas (o divides) los valores **sin signos**, y después pones el **signo con la regla**:",
      "Fig:signos",
      "En símbolos: $(-6) \\cdot 5 = -30$ · $(-6) \\cdot (-5) = +30$ · $(+30) : (-5) = -6$ · $(-30) : (-5) = +6$. La división funciona con la **misma regla** que la multiplicación — por eso en la ficha del libro un solo vistazo a los signos te dice si el resultado llevará $+$ o $-$ antes de calcular nada.",
      "RAW:<table><caption>Cuidado con los paréntesis y las potencias</caption><thead><tr><th>Se escribe</th><th>Vale</th><th>Por qué</th></tr></thead><tbody><tr><td>$(-2)^2$</td><td>$+4$</td><td>El cuadrado es de TODO el paréntesis: $(-2)\\cdot(-2)$.</td></tr><tr><td>$-2^2$</td><td>$-4$</td><td>Sin paréntesis, el cuadrado va solo al $2$ y el signo menos se aplica después.</td></tr><tr><td>$(-2)^3$</td><td>$-8$</td><td>Tres factores negativos → impar → negativo.</td></tr></tbody></table>",
      "Propiedad que se usa sin nombrarla en los combinadas: el producto con **cualquier factor $0$** da $0$ — así que en una cadena larga como $(-3) \\cdot 0 \\cdot (+9)$ no hace falta calcular nada. Y recuerda el orden del apartado 5: potencias antes que productos, productos antes que sumas.",
    ],
    ej: [
      "(−6)·5 = −30 · (−6)·(−5) = +30 · (−30):5 = −6.",
      "(−1)·(−2)·(−3) = **−6** (impar de negativos).",
      "La temperatura baja 3 °C cada hora durante 5 horas: 5·(−3) = **−15 °C** en total.",
    ],
  },
];

// Actividades: 4 por apartado. nv = [2ºESO, 1ºESO, 6º, 5º] (siempre 4 niveles).
export const ACTS: Record<string, Act[]> = {
  "01-introduccion": [
    {
      t: "Clasifica la situación", d: "Escribir cada situación real con su signo.", ic: "etiquetas", ln: [-10, 10, [[-5, "−5", "rojo"], [5, "+5", "verde"]]],
      nv: [
        { p: ["**a)** Escribe con signo: 5 °C bajo cero · un buzo a 18 m bajo el mar · ingreso de 30 € · 400 m de altitud.", "**b)** Inventa dos situaciones nuevas: una positiva y una negativa.", "**c)** ¿Cuál de tus dos números está más cerca del 0? Justifícalo."],
          s: ["**a)** −5 °C · −18 m · +30 € · +400 m.", "**b)** Personal; válida si el signo cuadra.", "**c)** El de **valor absoluto menor**: si escribiste −5 y −18, −5 está más cerca del 0."] },
        { p: ["**a)** Escribe con signo: 5 °C bajo cero · buzo a 18 m bajo el mar · ingreso de 30 €.", "**b)** Inventa UNA situación (pista: cosas que suben… o que se deben)."],
          s: ["**a)** −5 °C · −18 m · +30 €.", "**b)** Personal con signo correcto."],
          ad: "3 ítems (se retira altitud, ambigua al principio) y una sola invención con pista verbal." },
        { p: ["**a)** Une cada tarjeta del dibujo con su frase: «bajo cero», «deuda», «dinero que entra».", "**b)** Copia el número con signo bajo cada frase."],
          s: ["**a)** −3 °C → bajo cero · −11 € → deuda · +20 € → dinero que entra.", "**b)** Se comprueba con el dibujo."],
          ad: "Emparejar y copiar: el signo se copia del modelo, todavía no se genera." },
        { p: ["**a)** Señala con el dedo las tarjetas «bajo cero o deudas». ¿Cuántas?", "**b)** Copia: «−3 = tres bajo cero» y «−11 = debo 11»."],
          s: ["**a)** Dos: −3 °C y −11 €.", "**b)** Copia correcta de las dos frases."],
          ad: "Gesto y voz antes que número: señalar y copiar con dictado del modelo." },
      ],
    },
    {
      t: "Cuatro ciudades, cuatro signos", d: "Temperaturas reales de ciudades del mundo.", ic: "globos", ln: [-20, 20, [[-19, "Moscú", "rojo"], [-7, "Oslo", "rojo"], [8, "Xàtiva", "verde"], [14, "Valencia", "verde"]]],
      nv: [
        { in: "Mínimas de hoy: Oslo −7 °C · Valencia +14 °C · Moscú −19 °C · Xàtiva +8 °C.",
          p: ["**a)** Coloca las cuatro ciudades en la recta horizontal.", "**b)** Ordénalas de más fría a menos fría.", "**c)** ¿Qué ciudad está más cerca de 0? ¿Y qué diferencia hay entre la más fría y la más cálida?"],
          s: ["**b)** Moscú < Oslo < Xàtiva < Valencia.", "**c)** Xàtiva (+8) · diferencia: 14 − (−19) = **33 °C**."] },
        { p: ["**a)** Coloca Oslo (−7) y Valencia (+14) en la recta impresa.", "**b)** ¿Qué ciudad está más fría? Rodea.", "**c)** ¿Cuántos grados hay de una a otra? Cuenta saltos en la recta."],
          s: ["**b)** Oslo.", "**c)** 7 + 14 = **21 grados**."],
          ad: "Dos ciudades, recta impresa y distancia contada con saltos en vez de restada." },
        { p: ["**a)** Une cada termómetro de la pizarra con la ciudad que le toca (−19 Moscú, −7 Oslo, +8 Xàtiva, +14 Valencia).", "**b)** Rodea la ciudad más fría."],
          s: ["**a)** Correspondencia correcta de los cuatro pares.", "**b)** Moscú."],
          ad: "Emparejar con imagen; la comparación se resuelve rodéando, sin restar." },
        { p: ["**a)** Pega la pegatina de cada ciudad sobre la recta gigante de la mesa (el profe dicta la temperatura).", "**b)** Copia: «Oslo = −7 = siete bajo cero»."],
          s: ["**a)** Cuatro pegatinas colocadas con ayuda del dictado.", "**b)** Copia correcta."],
          ad: "Manipulativo y oral: la recta es gigante y el número se dicta antes de escribirse." },
      ],
    },
    {
      t: "¿Verdad o mentira?", d: "Afirmaciones sobre negativos para discutir en pareja.", ic: "verdad",
      nv: [
        { p: ["Di si son verdaderas o falsas y corrige las falsas:", "**a)** Todo número negativo es menor que 0.", "**b)** −7 es mayor que −3.", "**c)** −5 °C significa «5 grados bajo cero».", "**d)** El 0 es un número positivo."],
          s: ["**a)** Verdadera.", "**b)** Falsa: −7 < −3 (está más a la izquierda).", "**c)** Verdadera.", "**d)** Falsa: el 0 no es ni positivo ni negativo."] },
        { p: ["**a)** Todo negativo es menor que 0: ¿verdad o mentira?", "**b)** −7 es mayor que −3: ¿verdad o mentira? Dibuja la recta si dudas.", "**c)** −5 °C = «bajo cero»: ¿verdad o mentira?"],
          s: ["**a)** Verdad.", "**b)** Mentira.", "**c)** Verdad."],
          ad: "Tres afirmaciones, sin el 0 (concepto fronterizo que se asienta después) y con permiso explícito de recta." },
        { p: ["**a)** Con las tarjetas rojo/verde: pon en VERDE las frases verdaderas y en ROJO las falsas: «−2 está bajo cero» · «−9 es más que −2».", "**b)** Corrige en una palabra la falsa."],
          s: ["**a)** Verde: la primera. Roja: la segunda.", "**b)** «menos» (−9 es **menos** que −2)."],
          ad: "El color sustituye a verdad/mentira escrito; la corrección es de una sola palabra." },
        { p: ["**a)** Colorea el termómetro: azul lo que está bajo cero, rojo lo que no. Tarjetas: −2 y 4.", "**b)** Copia la frase buena: «−2 está bajo cero»."],
          s: ["**a)** Azul la −2, rojo la 4.", "**b)** Copia correcta."],
          ad: "Bajo cero / no bajo cero como tarea de colorear; la frase se copia, no se produce." },
      ],
    },
    {
      t: "Inventor de negativos", d: "Crear tú la situación que esconde un número.", ic: "letras",
      nv: [
        { p: ["**a)** Inventa una situación real para cada número: −12 · +25 · −1.", "**b)** Escríbelas en pasado como si fueran la noticia de un día.", "**c)** Cambia con tu compañero los números: ¿su situación encaja con tu número? ¿Le falta unidad (€, °C, m)?"],
          s: ["**a-c)** Respuestas personales: vale si el signo y la unidad concuerdan (−12 € de descubierto, +25 m de globo, −1 °C al anochecer…)."] },
        { p: ["**a)** Inventa una situación para −8.", "**b)** Ponle la unidad correcta: ¿son euros, grados o metros?"],
          s: ["Personal. Vale si «bajo, debe o debajo» acompaña al −8."],
          ad: "Un solo número y la unidad como pregunta cerrada de tres opciones." },
        { p: ["**a)** De estas tres tarjetas, elige la situación que va con −4: «subo 4 pisos», «debo 4 €», «tengo 4 €».", "**b)** Dibuja la tarjeta elegida."],
          s: ["**a)** «Debo 4 €».", "**b)** Dibujo coherente con la deuda."],
          ad: "Elegir entre tres tarjetas dadas en vez de crear: la creación se sustituye por dibujar." },
        { p: ["**a)** El profe enseña una situación («me faltan 4 euros») y tú levantas la tarjeta ROJA si es negativo o VERDE si es positivo.", "**b)** Copia la frase con su número: «me faltan 4 € = −4 €»."],
          s: ["**a)** ROJA.", "**b)** Copia correcta."],
          ad: "Respuesta con tarjeta de color (oral-visual) y copia final como cierre." },
      ],
    },
  ],
  "02-recta": [
    {
      t: "Temperaturas en la semana", d: "Ordenar y moverse por la recta con una semana de enero.", ic: "termometro", ln: [-8, 4, [[-6, "mié", "rojo"], [-3, "lun", "rojo"], [0, "mar", "azul"], [2, "jue", "verde"]]],
      nv: [
        { in: "Mínimas de una semana de enero en Morella: lunes −3 °C · martes 0 °C · miércoles −6 °C · jueves 2 °C · viernes −1 °C.",
          p: ["**a)** Ordénalas de más fría a menos fría.", "**b)** ¿Qué día hizo más calor y qué día más frío?", "**c)** Diferencia de temperatura entre miércoles y jueves.", "**d)** Sábado −4 °C; el domingo subió 5. ¿Qué marcó el termómetro?"],
          s: ["**a)** −6 < −3 < −1 < 0 < 2.", "**b)** Jueves (2 °C) / miércoles (−6 °C).", "**c)** 2 − (−6) = 2 + 6 = **8 °C**.", "**d)** −4 + 5 = **1 °C**."] },
        { p: ["**a)** Marca en la recta impresa: sábado −2 °C, domingo −5 °C.", "**b)** ¿Qué día hacía más frío? Rodea: sábado / domingo.", "**c)** El lunes subió a 0: ¿cuántos grados subió desde el domingo?"],
          s: ["**a)** −5 a la izquierda de −2.", "**b)** Domingo.", "**c)** **5 grados**."],
          ad: "Dos días, recta impresa, opción cerrada en b) y el 0 como referencia final." },
        { p: ["**a)** Escribe lo que marca el termómetro del dibujo: −2 °C.", "**b)** A las 12 subió 6 grados: dibuja el salto en la recta y escribe la temperatura.", "**c)** ¿Más fría la mañana (−2) o la noche (−4)?"],
          s: ["**b)** −2 + 6 = **4 °C**.", "**c)** La noche."],
          ad: "Una operación sola y apoyo visual directo del termómetro." },
        { p: ["**a)** Copia la temperatura del dibujo: −2 °C. Dilo en voz alta: «dos grados bajo cero».", "**b)** Pegatina en −2 y otra 6 saltos más arriba.", "**c)** Completa: «al mediodía eran ___ grados»."],
          s: ["**b)** Pegatinas en −2 y +4.", "**c)** «…eran **4**»."],
          ad: "Recta recortable física; solo se anda hacia arriba." },
      ],
    },
    {
      t: "La rana saltarina", d: "Sumas y restas como saltos sobre la regla.", ic: "rana", ln: [-10, 10, [[-4, "salida", "violeta"], [2, "", "verde"]]],
      nv: [
        { in: "Una rana está en el −4 de la recta.",
          p: ["**a)** Salta +6: ¿dónde cae? Escribe la operación.", "**b)** Desde ahí salta −3: ¿dónde queda ahora?", "**c)** ¿Qué salto único la llevaría del −4 al destino final? Compruébalo con los dos saltos."] ,
          s: ["**a)** (−4) + 6 = **+2**.", "**b)** 2 − 3 = **−1**.", "**c)** Del −4 al −1: +3 — que es +6 − 3. Cuadra."] },
        { p: ["**a)** La rana está en −4 y salta +6. Marca con un punto dónde cae y escríbelo.", "**b)** Desde ahí salta −3. ¿Dónde queda?"],
          s: ["**a)** En **+2**.", "**b)** En **−1**."],
          ad: "Sin apartado c) (comprobación algebraica): los saltos se marcan a mano en la recta impresa." },
        { p: ["**a)** La rana sale del 2. Salta 4 a la derecha: ¿dónde cae?", "**b)** Ahora salta 7 a la izquierda: ¿dónde acaba?"],
          s: ["**a)** En 6.", "**b)** De 6 a la izquierda 7: **−1**."],
          ad: "Salidas en positivo; la segunda resta se resuelve contando saltos con el dedo." },
        { p: ["**a)** Mueves la rana-imán: del 2, cuatro casillas a la derecha. Di dónde está.", "**b)** Siete a la izquierda (el profe te ayuda con los dedos). Di la casilla final.", "**c)** Pega la etiqueta del número final."],
          s: ["**a)** En 6.", "**b)** En −1.", "**c)** Etiqueta «−1»."],
          ad: "Rana de imán sobre recta de suelo; se dice antes que se escriba; la etiqueta cierra." },
      ],
    },
    {
      t: "El mapa del tesoro", d: "Seguir instrucciones de pasos por la recta-tesoro.", ic: "tesoro", ln: [-8, 8, [[3, "¡X!", "ambar"]]],
      nv: [
        { in: "El mapa dice: empieza en el +3 y aplica los pasos.",
          p: ["**a)** Paso 1: −7 · Paso 2: +9. ¿Dónde está el tesoro?", "**b)** Inventa TÚ un mapa de dos pasos que acabe en −5. Escríbelo como el del ejercicio (empieza en… paso…, paso…).", "**c)** Intercámbialo con un compañero: ¿sale su tesoro donde dice?"],
          s: ["**a)** 3 − 7 = −4 · −4 + 9 = **+5**. Tesoro en el 5.", "**b-c)** Personal: vale si los dos pasos llevan a −5 (p. ej. empezar en 0, −3, −2)."] },
        { p: ["**a)** Empiezas en +3: paso 1, baja a −4. ¿Cuántos pasos diste y en qué dirección?", "**b)** Paso 2: +9. ¿Dónde está el tesoro?"],
          s: ["**a)** 7 pasos a la izquierda (−7).", "**b)** **5**."],
          ad: "El mapa está medio dado: se describe el salto en vez de calcularlo a ciegas." },
        { p: ["**a)** Con el dedo en el +3: mueve 7 casillas a la izquierda. ¿Dónde estás?", "**b)** Ahora 9 a la derecha. Rodea la casilla del tesoro."],
          s: ["**a)** −4.", "**b)** 5 (rodeado)."],
          ad: "Regla física y dedo: contar en vez de restar mentalmente." },
        { p: ["**a)** El profe lee el mapa: «del 3, siete casillas a la izquierda». Mueve la ficha. Di dónde estás.", "**b)** «Nueve a la derecha». Mueve. Pega la estrella en la casilla final."],
          s: ["**a)** −4.", "**b)** 5, con estrella."],
          ad: "Dictado oral del mapa; la estrella física marca la respuesta." },
      ],
    },
    {
      t: "Hielo y deshielo", d: "La temperatura de un congelador a lo largo del día.", ic: "congelador", ln: [-20, 2, [[-18, "8h", "rojo"], [-15, "10h", "azul"], [-14, "9h", "azul"], [-9, "11h", "verde"]]],
      nv: [
        { in: "Un congelador industrial trabaja a −18 °C. Hoy, una puerta mal cerrada subió su temperatura: −18 → −14 → −15 → −9 → −2 (una por hora, de 8 a 12 h).",
          p: ["**a)** Coloca los cinco valores en la recta horizontal.", "**b)** ¿De qué hora a qué hora subió más la temperatura? ¿Cuánto subió en esa hora?", "**c)** Estando a −9 a las 11, la cámara de mantenimiento la devuelve a −18. ¿Cuánto tuvo que bajar? ¿Cuántos grados de recorrido total suma el día (subidas + bajada)?"],
          s: ["**b)** De 11 a 12 h: subió **7 °C** (de −9 a −2).", "**c)** Bajó **9 °C** · recorrido total del día: 4 + 1 + 6 + 7 + 9 = **27 °C** de camino (subidas y bajadas)."] },
        { p: ["**a)** Coloca −18, −14, −15 y −9 en la recta impresa.", "**b)** ¿A qué hora estaba más frío (−18 a las 8 o −9 a las 11)?", "**c)** Para volver a −18 desde −9, ¿cuántos grados debe bajar?"],
          s: ["**a)** Orden: −18, −15, −14, −9.", "**b)** A las 8.", "**c)** 9 grados."],
          ad: "Se quita el valor intermedio −2 (los números grandes redondos ayudan) y el cálculo de recorrido total." },
        { p: ["**a)** Pinta azul las temperaturas por debajo de −10 (−18, −15, −14) en la recta impresa.", "**b)** ¿Dónde hacía más frío, a las 8 o a las 12? Rodea la hora."],
          s: ["**b)** A las 8 (−18)."],
          ad: "La consigna es pintar (umbral dado por el profe) y una sola comparación." },
        { p: ["**a)** Con la recta de la mesa, pon la pegatina helada en −18. Pégala.", "**b)** Copia la frase: «−18 = 18 bajo cero»."],
          s: ["**a)** Pegatina en −18.", "**b)** Copia correcta."],
          ad: "Un solo número, puesto con pegatina y copia de lectura." },
      ],
    },
  ],
  "03-comparacion": [
    {
      t: "Compara con signos", d: "Mayor, menor o igual en cinco pares.", ic: "signos",
      nv: [
        { p: ["**a)** Compara con <, > o =: −4 ___ −9 · 0 ___ −2 · −7 ___ 3.", "**b)** Compara: |−5| ___ |+5| · |−2| ___ −8.", "**c)** Escribe un número mayor que −6 y menor que −2.", "**d)** Ordena de menor a mayor: 3, −5, 0, −1, 7."],
          s: ["**a)** −4 > −9 · 0 > −2 · −7 < 3.", "**b)** |=| (los dos 5) · −2 > −8 (valor absoluto 2, y −2 > −8).", "**c)** −5, −4 o −3.", "**d)** −5 < −1 < 0 < 3 < 7."] },
        { p: ["**a)** Compara con signos: −4 ___ −9 · 0 ___ −2 · −7 ___ 3.", "**b)** Escribe un número entre −6 y −2.", "**c)** Ordena: −5, 0, 3."],
          s: ["**a)** > · > · <.", "**b)** −5, −4 o −3.", "**c)** −5 < 0 < 3."],
          ad: "Se retira valor absoluto y los pares de 4 elementos: la recta impresa es material de apoyo permitido." },
        { p: ["**a)** Pinta en la recta: −4 (rojo) y −9 (verde). ¿Cuál está más a la derecha?", "**b)** Rodea el mayor en cada pareja: −4/−9 · −7/3."],
          s: ["**a)** El rojo, −4.", "**b)** −4 y 3."],
          ad: "Se elimina la notación < > escrita: «rodea el mayor» hace el trabajo." },
        { p: ["**a)** Con pegatinas en la recta de la mesa: −4 y −9. Señala el que está más a la derecha.", "**b)** Pega la tarjeta «MAYOR» sobre el número que toca.", "**c)** Di: «−4 es mayor que −9»."],
          s: ["**a)** −4.", "**b)** Tarjeta sobre −4.", "**c)** Frase bien dicha."],
          ad: "Todo con recta física, tarjeta y frase oral copia del modelo." },
      ],
    },
    {
      t: "¿Quién está mejor?", d: "Comparar saldos y temperaturas interpretando, no calculando.", ic: "banco",
      nv: [
        { p: ["**a)** Dos cuentas: −8 € y −14 €. ¿Cuál está mejor? Explica con «debe».", "**b)** Dos termómetros: −5 °C y +2 °C. ¿Cuál está más cerca de 0? ¿Cuánto falta a cada uno para llegar al 0?", "**c)** ¿Cuánto debe sumar la cuenta de −14 € para igualar a la de −8 €?"],
          s: ["**a)** La de −8: debe 8 € frente a 14 €.", "**b)** El de +2 (faltan 2, mientras al de −5 le faltan 5).", "**c)** 6 € (−8 − (−14) = 6)."] },
        { p: ["**a)** Cuenta A: −8 € · Cuenta B: −14 €. ¿Cuál está mejor? Rodea.", "**b)** ¿Cuánto le falta a la peor para llegar a 0?"],
          s: ["**a)** La A.", "**b)** 14 €."],
          ad: "Se quita la resta de saldos (c): la comparación se rodea y la distancia al 0 se cuenta." },
        { p: ["**a)** Rodea la cuenta mejor: −8 € / −14 €.", "**b)** Pinta la temperatura más cercana a 0: −5 °C / +2 °C (recta impresa)."],
          s: ["**a)** −8 €.", "**b)** +2 °C."],
          ad: "Dos rodeos/pintados con la recta delante; sin justificación escrita." },
        { p: ["**a)** Con las monedas de juguete: la hucha A debe 8 (fichas rojas) y la B debe 14. ¿Cuál está mejor? Pon la tarjeta «MEJOR» encima.", "**b)** Copia: «debo menos, estoy mejor»."],
          s: ["**a)** La A (8 fichas rojas).", "**b)** Copia correcta."],
          ad: "Deudas como fichas físicas; la regla se copia en voz-alta-escrita." },
      ],
    },
    {
      t: "Entre ¿qué número y qué número?", d: "Acotar valores: el juego de la temperatura justa.", ic: "recta",
      nv: [
        { p: ["**a)** Escribe un entero entre −6 y −2. ¿Hay más de uno? ¿Cuántos?", "**b)** Escribe el menor de los enteros mayores que −4.", "**c)** Tu primo dice: «hay números entre −1 y 0». ¿Le corriges? ¿Y entre −1 y 0 **con decimales**? Piensa: ¿esto eran números enteros?"],
          s: ["**a)** −5, −4, −3 → **3 números**.", "**b)** −3.", "**c)** En los enteros, no hay ninguno entre −1 y 0; si metemos decimales, sí (−0,5). La lista de enteros no es continua."] },
        { p: ["**a)** Marca en la recta los enteros entre −6 y −2. ¿Cuántos hay?", "**b)** ¿Cuál es el más pequeño de los mayores que −4?"],
          s: ["**a)** Tres: −5, −4 y −3.", "**b)** −3."],
          ad: "Sin el debate final de densidad (c): se marca a mano y se cuenta." },
        { p: ["**a)** Pinta los números entre −5 y −1 en la recta impresa. ¿Cuántos?", "**b)** ¿Cuál es el de en medio?"],
          s: ["**a)** −4, −3, −2 → 3.", "**b)** −3."],
          ad: "Rango más pequeño y pregunta de «el de en medio» en lugar del acotado." },
        { p: ["**a)** Con las pegatinas del −5 al −1, pon solo las que están ENTRE −5 y −1. ¿Cuántas pegaste?", "**b)** Muestra con el dedo la del medio."],
          s: ["**a)** Tres (−4, −3, −2).", "**b)** La del −3."],
          ad: "Filtrar físicamente pegatinas; contar y señalar." },
      ],
    },
    {
      t: "Distancias al cero", d: "Valor absoluto como «cuánto falta para el 0».", ic: "verdad",
      nv: [
        { p: ["**a)** ¿A qué distancia del 0 están −7 y +7? ¿Son la misma?", "**b)** Ordena por distancia al 0 (mayor primero): −2, +6, −9, +1.", "**c)** ¿Es cierto que |−a| = |a| siempre? Pon tres ejemplos con a elegida por ti."],
          s: ["**a)** 7 los dos: misma distancia.", "**b)** −9, +6, −2, +1.", "**c)** Sí: |−3|=|3|=3, |−0|=|0|=0, |−10|=10."] },
        { p: ["**a)** Mide en la recta: ¿cuánto falta de −7 al 0? ¿Y de +7?", "**b)** ¿Cuál está más lejos del 0: −2 o +6?"],
          s: ["**a)** 7 y 7.", "**b)** +6."],
          ad: "La distancia se mide con la recta; sin notación | | escrita." },
        { p: ["**a)** En la recta impresa, cuenta con el dedo cuánto hay de −4 al 0 y de +4 al 0. ¿Igual?", "**b)** Rodea el que está más lejos del 0: −7 o +2."],
          s: ["**a)** 4 y 4: igual.", "**b)** −7."],
          ad: "Contar con el dedo y rodear; el concepto entra sin fórmula." },
        { p: ["**a)** Con la regla de la mesa: el profe dice −4; pon el dedo en el 0 y cuenta hasta su número. ¿Cuántos?", "**b)** Copia: «−4 está a 4 del cero»."],
          s: ["**a)** 4.", "**b)** Copia correcta."],
          ad: "Medición corporal y copia de la frase con la palabra «distancia» aún fuera." },
      ],
    },
  ],
  "04-suma-resta": [
    {
      t: "La cuenta del banco de Maria", d: "Ingresos, gastos y el descubierto.", ic: "banco", ln: [-20, 60, [[-11, "hoy", "rojo"], [45, "inicio", "verde"]]],
      nv: [
        { in: "Maria tiene 45 €. Esta semana:",
          p: ["**a)** Escribe con signo: lunes gasta 62 € · miércoles ingresa 20 € del abuelo · viernes gasta 14 € en el cine.", "**b)** Calcula su saldo del viernes.", "**c)** Interpreta el resultado si sale negativo.", "**d)** ¿Cuánto necesita el sábado para volver a saldo 0?"],
          s: ["**a)** +45, −62, +20, −14.", "**b)** 45 − 62 + 20 − 14 = **−11 €**.", "**c)** Descubierto: debe 11 €.", "**d)** 11 €."] },
        { p: ["**a)** Tabla INGRESOS(+)/GASTOS(−): tiene 40 €; ingresa 20 €; gasta 55 €.", "**b)** Dos tiempos: junta los ingresos y luego resta el gasto.", "**c)** Completa: «le sobran/faltan ___ €»."],
          s: ["**a)** +40, +20, −55.", "**b)** 60 − 55 = **+5 €**.", "**c)** «Sobran 5» (variante profe: gasto 65 → −5)."],
          ad: "Tabla estructurada, números redondos y cálculo en dos tiempos." },
        { p: ["**a)** Maria tiene 30 € y gasta 45 €. Dibuja la recta 0–50 y el salto hacia atrás.", "**b)** ¿Cuánto le falta?", "**c)** Escríbelo con signo: le faltan 15 → **−15 €**."],
          s: ["**b)** 15 €.", "**c)** −15 €."],
          ad: "Un movimiento; el negativo nace como nombre de lo que falta." },
        { p: ["**a)** Monedas de 5 €: 6 monedas vs juguete de 9 fichas. ¿Cuántas monedas faltan?", "**b)** Completa: «le faltan ___ €».", "**c)** Copia: «faltan 15 = −15»."],
          s: ["**a)** 3 monedas = 15 €.", "**b)** 15.", "**c)** −15."],
          ad: "Manipulativo: la resta se resuelve por correspondencia de monedas." },
      ],
    },
    {
      t: "Sube y baja la temperatura", d: "Cambios de temperatura como sumas y restas.", ic: "termometro", ln: [-10, 10, [[-4, "", "rojo"], [9, "", "verde"]]],
      nv: [
        { p: ["**a)** De −4 °C a 9 °C: ¿subió o bajó? ¿Cuántos grados?", "**b)** A las 6 estaba a 3 °C y bajó 8. ¿Temperatura a las 6+?", "**c)** De −3 a −7: ¿subió o bajó? ¿Cuánto? (Ojo: dos negativos — usa la recta antes de calcular.)"],
          s: ["**a)** Subió: 4 + 9 = **13 °C**.", "**b)** 3 − 8 = **−5 °C**.", "**c)** Bajó 4 (−7 está más a la izquierda)."] },
        { p: ["**a)** De −4 °C a 9 °C: cuenta en la recta cuántos grados subió.", "**b)** A las 6 había 3 °C y bajó 8: marca dónde queda."],
          s: ["**a)** 13 °C.", "**b)** −5 °C."],
          ad: "Se retira el caso c) (negativo→negativo sin paso por 0, el más confuso)." },
        { p: ["**a)** El termómetro marcaba −2 y ahora marca −6. ¿Subió o bajó? ¿Cuánto?", "**b)** Rodea el termómetro más frío: −6 / −2."],
          s: ["**a)** Bajó 4.", "**b)** −6."],
          ad: "Números pequeños, opción cerrada y la recta de apoyo siempre visible." },
        { p: ["**a)** Con el dado de temperaturas: −2. Tira el dado rojo (bajó 3): mueve el termómetro. Di: «ahora −5».", "**b)** Copia la pareja: «−2 − 3 = −5»."],
          s: ["**a)** «Ahora −5».", "**b)** Copia correcta."],
          ad: "El cambio se ejecuta (termómetro de cartón) antes de escribirse." },
      ],
    },
    {
      t: "El edificio de 7 plantas", d: "Subo y bajo entre plantas y sótanos.", ic: "ascensor", ln: [-2, 5, [[-2, "sale", "violeta"], [1, "", "verde"]]],
      nv: [
        { p: ["**a)** Sale del −2, sube 5 y baja 3: ¿en qué planta queda? Escribe la operación completa antes.", "**b)** Desde la planta 1, ¿cuántas plantas debe bajar para llegar al −2?", "**c)** Escribe una ruta (dos movimientos) para ir del −1 a la planta 3 sin pisar el 0… ¿es posible? Justifica."],
          s: ["**a)** (−2)+5−3 = **0**.", "**b)** 3 plantas.", "**c)** No: para pasar de negativo a positivo hay que cruzar el 0; sube +4 y no hay forma de saltárselo."] },
        { p: ["**a)** Sale del −2, sube 5: ¿dónde está?", "**b)** Desde ahí baja 3: ¿planta final?"],
          s: ["**a)** 3.", "**b)** 0."],
          ad: "Un movimiento por pregunta; sin el reto conceptual del apartado c)." },
        { p: ["**a)** El ascensor está en −1. Sube 4. Rodea la planta de llegada: −4 / 0 / 3.", "**b)** Ahora baja 2: ¿a qué planta va?"],
          s: ["**a)** 3.", "**b)** 1."],
          ad: "Primera respuesta con opción cerrada impresa." },
        { p: ["**a)** Maqueta: imán en −1; sube 4 casillas. Di la planta.", "**b)** Baja 2. Pega la etiqueta final."],
          s: ["**a)** Planta 3.", "**b)** «1»."],
          ad: "Recorrido físico; la etiqueta es la única escritura." },
      ],
    },
    {
      t: "La distancia entre dos puntos", d: "Restar = medir distancia con la recta.", ic: "recta", ln: [-10, 10, [[-7, "", "rojo"], [5, "", "verde"]]],
      nv: [
        { p: ["**a)** Distancia entre −7 y 5 (cuenta o calcula: 5 − (−7)).", "**b)** Distancia entre −3 y −9.", "**c)** Dos ciudades: una a −12 m (mina) y otra a +340 m (pueblo). ¿Desnivel? Escribe la operación ANTES."],
          s: ["**a)** 12 (7 + 5).", "**b)** 6.", "**c)** 340 − (−12) = 352 m."] },
        { p: ["**a)** Entre −7 y 5: cuenta los saltos en la recta impresa.", "**b)** Entre −3 y −9: cuenta los saltos."],
          s: ["**a)** 12.", "**b)** 6."],
          ad: "Todo se cuenta en la recta; sin fórmula de resta de negativos." },
        { p: ["**a)** Coloca una cuerda entre −7 y 5 en la recta gigante. ¿Cuántas casillas ocupa?", "**b)** ¿Entre −3 y −9 cuántas?"],
          s: ["**a)** 12.", "**b)** 6."],
          ad: "Medir con cuerda: el número aparece contando casillas." },
        { p: ["**a)** Cuerda del −2 al 0. Cuenta casillas. Di: «dos».", "**b)** Copia: «del −2 al 0 hay 2»."],
          s: ["**a)** 2.", "**b)** Copia correcta."],
          ad: "Tramo corto con el 0 como final seguro." },
      ],
    },
  ],
  "05-combinadas": [
    {
      t: "El ascensor del parking", d: "Encadenar subidas y bajadas con paréntesis.", ic: "ascensor", ln: [-4, 6, [[-2, "sale", "violeta"], [4, "llega", "verde"]]],
      nv: [
        { in: "El ascensor empieza en el sótano 2 (−2): sube 5, baja 3 y vuelve a subir 4.",
          p: ["**a)** Escribe la operación con signos y paréntesis.", "**b)** ¿En qué planta queda?", "**c)** Desde ahí: ¿cuántas plantas para llegar al −1?", "**d)** Un compañero dice «−2+5−3+4 = 4». ¿Le confirmas o le corriges? Justifica."] ,
          s: ["**a)** (−2)+5−3+4.", "**b)** −2 → +3 → 0 → +4: **planta 4**.", "**c)** 4 − (−1) = **5 plantas**.", "**d)** 3 − 3 + 4 = 4: **confirmas**."] },
        { p: ["**a)** Sale de −1: sube 4. Marca la parada.", "**b)** Baja 2: ¿planta final?"],
          s: ["**a)** 3.", "**b)** 1."],
          ad: "Dos movimientos sin paréntesis: se introducen cuando la cadena ya domina." },
        { p: ["**a)** Sale de −2 y sube 3. Traza la flecha en el dibujo.", "**b)** (−2)+3 = ___ .", "**c)** ¿Quedó por encima del 0? Sí/No."],
          s: ["**b)** 1.", "**c)** Sí."],
          ad: "Una suma sola y verificación Sí/No con el dibujo." },
        { p: ["**a)** Imán en −2 de la maqueta; sube 3 casillas.", "**b)** Di: «estoy en la planta 1».", "**c)** Etiqueta las dos paradas: «−2» y «1»."],
          s: ["**b)** Frase bien dicha.", "**c)** Etiquetas correctas."],
          ad: "Maqueta + verbalización; escribir solo las etiquetas." },
      ],
    },
    {
      t: "Cartas positivas y negativas", d: "Juego de sumar cartas rojas y verdes.", ic: "dados", ln: [-12, 12, [[-5, "", "rojo"], [3, "", "verde"]]],
      nv: [
        { in: "Cartas verdes = positivos · cartas rojas = negativos. Tu mano: +7, −3, −5, +1.",
          p: ["**a)** Suma TU mano: ¿puntos totales?", "**b)** Tu rival tiene −2, +6, −8, +4. ¿Quién gana? ¿Por cuánto?", "**c)** Con dos cartas solo, sácalas: una roja de 9 y una verde de 4: ¿total? ¿Qué carta tendrías que tirar para quedarte en 0?"],
          s: ["**a)** 7 − 3 − 5 + 1 = **0**.", "**b)** Rival = 0: **empate**; 0 − 0 = 0.", "**c)** −9 + 4 = −5 · necesitas un +5."] },
        { in: "Mano: +7, −3, −5, +1 (verdes suman, rojas restan).",
          p: ["**a)** ¿Cuánto suman? Hazlo por colores: verdes por un lado, rojas por otro.", "**b)** ¿Qué dos cartas quitarías para quedarte con 0? Comprueba."],
          s: ["**a)** 8 − 8 = **0**.", "**b)** No hay ninguna pareja que sume 0 (+7−3=4, +7−5=2, +7+1=8, −3−5=−8, −3+1=−2, −5+1=−4): **la única forma de quedarse en 0 es quitar las cuatro cartas**, porque la mano ya sumaba 0."] },
        { p: ["**a)** Manos de dos cartas: verde 6 + roja 2 → ¿total?", "**b)** Verde 1 + roja 4 → ¿total?"],
          s: ["**a)** 4.", "**b)** −3."],
          ad: "Solo dos cartas y un verde una roja: sin agrupar." },
        { p: ["**a)** Saca dos cartas grandes: verde de 2, roja de 5: ponlas sobre la recta de la mesa con los dedos.", "**b)** Di el total. El profe escribe la operación.", "**c)** Copia: «2 − 5 = −3»."],
          s: ["**b)** −3.", "**c)** Copia correcta."],
          ad: "El cálculo lo hace el profe y el alumno copia la igualdad." },
      ],
    },
    {
      t: "Excursión a la montaña", d: "Etapas de subida y bajada con altitud final.", ic: "aguila",
      nv: [
        { in: "Salimos del refugio a +1 250 m: subimos 380 m, bajamos 520 m, volvemos a subir 170 m.",
          p: ["**a)** Escribe la operación encadenada.", "**b)** Altitud final: ¿por encima del refugio? ¿Cuánto?", "**c)** Para volver al refugio: ¿subes o bajas? ¿Cuánto?"],
          s: ["**a)** 1 250 + 380 − 520 + 170.", "**b)** 1 280 m: **+30** sobre el refugio.", "**c)** Bajas 30."] },
        { in: "Refugio a 1 250 m; subes 100 y bajas 180.",
          p: ["**a)** ¿Altitud final?", "**b)** ¿Estás por encima o por debajo del refugio? ¿Cuánto?"],
          s: ["**a)** 1 170 m.", "**b)** Por debajo: 80 m."],
          ad: "Dos etapas redondas; la comparación se contesta sin restar el refugio." },
        { p: ["**a)** Dibuja en la montaña de la ficha: salgo de 250, subo 100. ¿Dónde?", "**b)** Bajo 180: ¿dónde acabo?"],
          s: ["**a)** 350.", "**b)** 170."],
          ad: "Altitudes pequeñas (0–400) y flechas dibujadas." },
        { p: ["**a)** Muñeco en la ladera: el profe lee «sube 100»; mueve. ¿Dónde?", "**b)** «Baja 180»: mueve y di el número.", "**c)** Copia: «estoy en 170»."],
          s: ["**b)** 170.", "**c)** Copia correcta."],
          ad: "Recorrido físico guiado; copia final." },
      ],
    },
    {
      t: "Caza el error", d: "Corregir operaciones encadenadas mal resueltas.", ic: "verdad",
      nv: [
        { p: ["Un compañero resolvió. Encuentra el error, di en qué paso está y escribe la versión correcta:", "**a)** (−5) + 3 − (−2) → −5 + 3 − 2 = −4", "**b)** 8 − (3 + 1) − 2 → 8 − 3 + 1 − 2 = 4", "**c)** (−10) : 2 · 3 → −10 : 6 = −1… y dice que el orden de · y : no importa."],
          s: ["**a)** Error en el signo: −(−2) = +2 → −5+3+2 = **0**.", "**b)** El paréntesis con el menos delante: 8−4−2 = **2**.", "**c)** Izquierda a derecha: (−10):2 = −5 · −5·3 = **−15** — el orden sí importa."] },
        { p: ["**a)** Él hizo: −5 + 3 − 2. Le faltó un signo con el paréntesis −(−2). Corrige el resultado.", "**b)** 8 − (3+1) − 2: ¿sale 4 o 2?"],
          s: ["**a)** −5 + 3 + 2 = **0**.", "**b)** 2."],
          ad: "El error está señalado ya: queda corregir, no detectar." },
        { p: ["**a)** Tachla la operación mal: 4 + 5 · 2 = 18 / = 14 (una es correcta).", "**b)** Comprueba la buena con la calculadora."],
          s: ["**a)** Está mal el 18 (primero el producto): 14.", "**b)** 14 confirmado."],
          ad: "Un error por página y opción doble; comprobación con calculadora." },
        { p: ["**a)** El profe escribe dos operaciones y una sale mal (2 + 3 · 4 = 14). Señala cuál.", "**b)** Copia la buena: 2 + 3 · 4 = **14**… ¡ojo, hoy el profe dice que esta SÍ es correcta! Copia la que dice el profe."],
          s: ["**a-b)** Copiar la igualdad que el profe marque como buena.", "**b)** 14."],
          ad: "Sin producción: el alumno copia la buena tras señalar." },
      ],
    },
  ],
  "06-problemas": [
    {
      t: "Valle, pueblo y dron", d: "Desniveles, temperaturas y un dron con paréntesis.", ic: "aguila", ln: [-150, 400, [[-120, "valle", "rojo"], [340, "pueblo", "verde"]]],
      nv: [
        { in: "Fondo del valle a −120 m; pueblo a +340 m.",
          p: ["**a)** Desnivel entre valle y pueblo.", "**b)** De 7 °C de mediodía a −4 °C de anochecer: ¿cuántos grados bajó?", "**c)** El dron sale del pueblo, sube 60 y baja 95: ¿altitud final? (operación antes de calcular)", "**d)** Responde c) en una frase completa con unidad."],
          s: ["**a)** 340 − (−120) = 340 + 120 = **460 m**.", "**b)** 7 − (−4) = **11 °C**.", "**c)** 340 + 60 − 95 = **305 m**.", "**d)** «El dron queda a 305 m sobre el nivel del mar, 35 m por debajo del pueblo»."] },
        { p: ["**a)** Valle −120, pueblo +340: ¿metros de uno a otro? (Pista: suma los dos números sin signos.)", "**b)** De 7 °C a −4 °C: ¿bajada? Haz la recta.", "**c)** 340 + 60 − 95 = ___"],
          s: ["**a)** 460 m.", "**b)** 11 °C.", "**c)** 305 m."],
          ad: "Pistas de procedimiento en cada apartado; la operación de c) viene montada." },
        { p: ["**a)** Rodea más alto: valle (−120) o pueblo (+340).", "**b)** En la recta 300–400: del pueblo, 60 arriba y 95 abajo. Escribe dónde acabas.", "**c)** ¿7 °C o −4 °C? Rodea el mayor."],
          s: ["**a)** Pueblo.", "**b)** 305.", "**c)** 7 °C."],
          ad: "El desnivel se convierte en rodeo; el resto con recta recortada al rango." },
        { p: ["**a)** Plastilina: valle bajo la mesa, pueblo encima. Etiqueta −120 y +340.", "**b)** Muñeco: 340 → +60 → −95 con la calculadora de cinta. Etiqueta final.", "**c)** Copia: «el pueblo a 340 m, el valle a −120 m»."],
          s: ["**a)** Etiquetas puestas.", "**b)** 305.", "**c)** Copia correcta."],
          ad: "Todo físico: debajo/encima = signo; el cálculo, con calculadora de cinta." },
      ],
    },
    {
      t: "El ascensor de la mina", d: "Problema minero con pozos de agua.", ic: "ascensor", ln: [-60, 20, [[-55, "", "rojo"], [8, "", "verde"]]],
      nv: [
        { in: "En una mina, el pozo norte está a −35 m y el sur a −52 m. Arriba, la caseta del ingeniero está a +8 m.",
          p: ["**a)** ¿Qué pozo está más profundo y a qué distancia del otro?", "**b)** Un cubo sube del pozo sur hasta la caseta: ¿cuántos metros recorre?", "**c)** Otros dos cubos hacen lo mismo desde −10 y −25: ¿de cuál se recorre menos? ¿Cuánto menos?"],
          s: ["**a)** El sur; −35 − (−52) = **17 m**.", "**b)** 8 − (−52) = **60 m**.", "**c)** Del de −10 se recorre menos: 8 − (−10) = 18 m frente a 8 − (−25) = 33 m → **15 m menos**."] },
        { p: ["**a)** Pozos a −35 y −52: cuenta la distancia en la recta.", "**b)** Cubo del sur (−52) hasta la caseta (+8): ¿metros?"],
          s: ["**a)** 17 m.", "**b)** 60 m."],
          ad: "Se elimina el apartado comparativo c): dos cálculos con recta." },
        { p: ["**a)** Rodea el pozo más profundo: −35 / −52.", "**b)** Cubo de −52 al +8: cuenta saltos. ¿Cuántos?"],
          s: ["**a)** −52.", "**b)** 60."],
          ad: "Rodeo + conteo; el pozo −10 fuera." },
        { p: ["**a)** Muñeco en −52 (el profe dicta); sube hasta +8 casilla a casilla. Cuenta.", "**b)** Copia: «el cubo sube 60 metros»."],
          s: ["**a)** 60.", "**b)** Copia correcta."],
          ad: "Recorrido corporal casilla a casilla; solo se copia la respuesta." },
      ],
    },
    {
      t: "El submarino y el buzo", d: "Profundidades con nivel del mar como cero.", ic: "tesoro", ln: [-70, 50, [[-45, "sonda", "rojo"], [20, "", "verde"]]],
      nv: [
        { in: "Un submarino a −45 m suelta una sonda que baja 25 m más. A la vez, un dron de salvamento sube desde la superficie hasta +12 m.",
          p: ["**a)** ¿Profundidad final de la sonda?", "**b)** ¿Qué distancia separa la sonda del dron?", "**c)** Si recuperan la sonda subiéndola a la mitad de su profundidad final: ¿a cuántos metros queda? ¿Subió menos que el dron?"],
          s: ["**a)** (−45) − 25 = **−70 m**.", "**b)** 12 − (−70) = **82 m**.", "**c)** −35 m: subió 35 · el dron subió 12: la sonda subió **más**."] },
        { p: ["**a)** Sonda: de −45 baja 25. ¿Dónde queda?", "**b)** Dron en +12: ¿cuántos metros de distancia hay hasta la sonda?"],
          s: ["**a)** −70.", "**b)** 82."],
          ad: "Sin apartado c) (mitades de negativos): dos operaciones directas." },
        { p: ["**a)** El submarino está a −45: pinta la zona bajo el mar en la recta impresa.", "**b)** La sonda baja 25 más. Rodea dónde queda: −20 / −70."],
          s: ["**b)** −70."],
          ad: "Pintar + rodear dos opciones." },
        { p: ["**a)** Fichas en la recta de suelo: submarino en −45, la profe dicta «baja 25». Mueve. ¿Dónde?", "**b)** Copia: «la sonda queda a −70 m»."],
          s: ["**a)** −70.", "**b)** Copia correcta."],
          ad: "Dictado y movimiento; la frase-respuesta se copia." },
      ],
    },
    {
      t: "La cuenta de toda la semana", d: "Problema completo de ingresos y gastos con tabla.", ic: "banco", ln: [-40, 60, [[-18, "jue", "rojo"], [52, "mar", "verde"]]],
      nv: [
        { in: "Lunes: saldo 30 €. Martes: +120 (nómina). Miércoles: −65 (compra). Jueves: −103 (recibo). Viernes: −? quiere cerrar la semana con saldo 0.",
          p: ["**a)** Saldo del miércoles.", "**b)** Saldo del jueves.", "**c)** ¿Qué necesita el viernes y cuánto? Escribe la operación final y la respuesta en frase."],
          s: ["**a)** 30 + 120 − 65 = **85 €**.", "**b)** 85 − 103 = **−18 €**.", "**c)** Ingresar **18 €**: −18 + x = 0 → x = 18. «El viernes debe ingresar 18 € para cerrar a cero»."] },
        { p: ["**a)** Lunes 30; martes +120: tabla ingresos/gastos.", "**b)** Miércoles −65: ¿saldo?", "**c)** Jueves −103: ¿sobran o faltan? ¿Cuánto?"],
          s: ["**a)** +150.", "**b)** 85.", "**c)** Faltan 18."],
          ad: "Tabla estructurada; la pregunta final (viernes) se convierte en «¿sobran o faltan?»." },
        { p: ["**a)** 30 + 120: suma primero los dos azules.", "**b)** Resultado − 65: ¿sale 85 o 25?", "**c)** 85 − 103: rodea: −18 / +18."],
          s: ["**a)** 150.", "**b)** 85.", "**c)** −18."],
          ad: "Cada paso con opción doble; los azules/rojos del código de color guían." },
        { p: ["**a)** Fichas azules (entra) y rojas (sale): pon 30 azules. Añade 120 azules (el profe te ayuda).", "**b)** Quita 65 azules: cuenta las que quedan.", "**c)** Pon las rojas que hacen falta para el recibo de 103 y pega la etiqueta «−18»."],
          s: ["**b)** 85.", "**c)** Etiqueta «−18»."],
          ad: "Semana como fichas de dos colores y etiqueta final." },
      ],
    },
  ],
  "07-multiplicacion": [
    {
      t: "La tabla de signos", d: "Aplicar la regla y encadenar productos.", ic: "signos",
      nv: [
        { p: ["**a)** Calcula: (−7)·4 · (−6)·(−5) · (−30):5.", "**b)** ¿Cuántos negativos hay en (−1)(−2)(−3)(−4) y cuánto sale? ¿Y si le añades un factor (−1) más?", "**c)** Calcula (−2)³ − (−3)² con cuidado: potencias primero.", "**d)** Explica por qué el producto de cuatro negativos es positivo."],
          s: ["**a)** −28 · +30 · −6.", "**b)** 4 (par) → +24 · con cinco: −24.", "**c)** −8 − 9 = **−17**.", "**d)** Los pares se emparejan en positivos: (−·−)=+, dos veces = +."] },
        { p: ["**a)** (−7)·4 · (−6)·(−5).", "**b)** (−1)(−2)(−3): ¿par o impar de negativos? ¿Signo? Calcula.", "**c)** (−2)³ = ___"],
          s: ["**a)** −28 · +30.", "**b)** 3 (impar) → −6.", "**c)** −8."],
          ad: "Sin división ni potencias con base negativa fuera; la regla de paridad se pregunta antes de calcular." },
        { p: ["**a)** (−4)·3: ¿positivo o negativo? Rodea y luego calcula.", "**b)** (−3)·(−5): rodea signo y calcula.", "**c)** 12 : (−2) = ___"],
          s: ["**a)** Negativo · −12.", "**b)** Positivo · +15.", "**c)** −6."],
          ad: "La regla se aplica con la tabla de signos a la vista (canal visual) y números ≤15." },
        { p: ["**a)** Dos dados: uno verde +2, uno rojo −4. Tira: producto = −8. Pon la etiqueta.", "**b)** Copia: «verde × rojo = rojo (negativo)»."],
          s: ["**a)** −8.", "**b)** Copia correcta."],
          ad: "Dados de colores: el color del resultado ES la regla; se copia la frase-ley." },
      ],
    },
    {
      t: "Baja 3 grados cada hora", d: "Multiplicar como cambio repetido.", ic: "termometro", ln: [-15, 5, [[-15, "fin", "rojo"], [0, "inicio", "verde"]]],
      nv: [
        { p: ["**a)** La temperatura baja 3 °C cada hora desde las 18:00 (0 °C). ¿Cuánto ha bajado a las 23:00? Operación.", "**b)** ¿Hora en que marcó −6 °C?", "**c)** Desde las 18 marca 0 y cada hora SUBE 2 hasta las 21, luego baja 4 hasta las 23: tabla horaria completa y temperatura final."],
          s: ["**a)** 5·(−3) = **−15 °C**.", "**b)** 20:00 (6 = 2 horas).", "**c)** 18:0 · 19:+2 · 20:+4 · 21:+6 · 22:+2 · 23:−2. Final **−2 °C**."] },
        { p: ["**a)** Baja 3 cada hora, 5 horas: ¿total?", "**b)** ¿A qué hora hizo −6 si empezó a bajar a las 18 con 0?"],
          s: ["**a)** −15 °C.", "**b)** 20:00."],
          ad: "Se retira el cambio de tendencia (sube/baja): un solo régimen de cambio." },
        { p: ["**a)** Cada hora pinta −3 en la tabla del dibujo (18, 19, 20…). ¿A las 20?", "**b)** ¿A las 22?"],
          s: ["**a)** −6 °C.", "**b)** −12 °C."],
          ad: "La tabla se pinta: multiplicar = repetir fila a fila." },
        { p: ["**a)** El profe mueve el termómetro −3 cada tic de reloj (5 tics). Di el número final.", "**b)** Copia: «5 × −3 = −15»."],
          s: ["**a)** −15.", "**b)** Copia correcta."],
          ad: "Ritmo corporal (tics) y copia de la multiplicación como ley." },
      ],
    },
    {
      t: "Potencias con signo", d: "(−2)², −2² y el peligro del exponente.", ic: "mago",
      nv: [
        { p: ["**a)** Calcula: (−3)² · (−3)³ · −3².", "**b)** ¿Cuándo es positiva (−2)ⁿ? Di la regla para n par e impar.", "**c)** Inventa un exponente para que (−5)^___ salga +625. ¿Es único?"],
          s: ["**a)** 9 · −27 · −9.", "**b)** Par → positiva; impar → negativa.", "**c)** n = 4 (único en enteros pequeños: (−5)⁴ = 625)."] },
        { p: ["**a)** (−2)² = ___ · (−2)³ = ___", "**b)** −2² = ___ . ¿Por qué es distinto de (−2)²?"],
          s: ["**a)** 4 · −8.", "**b)** −4: el signo de fuera se aplica al final."],
          ad: "Solo base 2 y exponentes ≤3, con la pregunta de por qué como oración." },
        { p: ["**a)** Con las tarjetas de potencias: (−2)² y −2²: ¿cuál vale +4? Rodea.", "**b)** (−2)³ = ___ (usa la tarjeta de ayuda)."],
          s: ["**a)** (−2)².", "**b)** −8."],
          ad: "Identificar entre dos tarjetas impresas en vez de calcular." },
        { p: ["**a)** El profe abre la caja de mago: «(−2) al cuadrado es +4». Levanta la tarjeta VERDE si lo dice bien.", "**b)** Copia la frase buena."],
          s: ["**a)** Verde.", "**b)** Copia correcta."],
          ad: "Verificar oralmente la frase-modelo y copiarla." },
      ],
    },
    {
      t: "La ficha del libro", d: "Adaptación del ejercicio 19: 5 multiplicaciones y 5 divisiones con la regla de los signos del libro de texto.", ic: "signos", regla: true,
      nv: [
        { in: "Ficha calcada del ejercicio del libro (números cambiados, misma estructura). Primero decide el color del signo, luego calcula el número.",
          p: ["**a)** Multiplica: (−9)·(+3) · (+8)·(+4) · (−7)·(−6) · (+5)·(−8) · (−4)·(−9).",
              "**b)** Divide: (−14) : (−7) · (+35) : (−5) · (−32) : (+4) · (+24) : (+8) · (−42) : (−6).",
              "**c)** Ordena los 5 resultados de a) de menor a mayor.",
              "**d)** Escribe dos operaciones (una multiplicación y una división) que den −8. ¿Son únicas?"],
          s: ["**a)** −27 · +32 · +42 · −40 · +36.",
              "**b)** +2 · −7 · −8 · +3 · +7.",
              "**c)** −40 < −27 < +32 < +36 < +42.",
              "**d)** No son únicas: p. ej. (−2)·4 = −8 y −16:2 = −8 — hay infinitas parejas."] },
        { in: "Igual que en el libro: decide primero el signo, luego el número.",
          p: ["**a)** Multiplica: (−9)·(+3) · (+8)·(+4) · (−7)·(−6).",
              "**b)** Multiplica: (+5)·(−8) · (−4)·(−9).",
              "**c)** Divide: (−14) : (−7) · (+35) : (−5) · (−32) : (+4).",
              "**d)** Divide: (+24) : (+8) · (−42) : (−6)."],
          s: ["**a)** −27 · +32 · +42.", "**b)** −40 · +36.", "**c)** +2 · −7 · −8.", "**d)** +3 · +7."],
          ad: "Las 10 cuentas se reparten en 4 grupos pequeños (menos carga visual por línea); mismos números y misma regla que el nivel de referencia." },
        { in: "Usa la tabla de colores de arriba: mismo color, resultado AZUL (+); colores distintos, ROJO (−).",
          p: ["**a)** Con los recuadros de la tabla: ¿el resultado de (−9)·3 sale azul o rojo? Rodea. Calcula el número.",
              "**b)** Haz lo mismo con (−7)·(−6).",
              "**c)** Completa: 14 : 7 = ___ · −14 : (−7) = ___",
              "**d)** Rodea las cuentas con resultado negativo: 35:(−5) · 24:8 · −32:4."],
          s: ["**a)** Rojo · −27.", "**b)** Azul · +42.", "**c)** 2 y +2.", "**d)** 35:(−5) y −32:4."],
          ad: "La regla entra por el color antes que por el signo escrito; 6 cuentas con la resta ya resuelta en c) como espejo positivo→negativo." },
        { in: "Fichas de colores: azul es positivo, rojo negativo. El profe dicta la cuenta; tú pones las dos fichas.",
          p: ["**a)** «−9 por 3»: pon ficha roja y azul. ¿El resultado se pone en la caja AZUL o ROJA?",
              "**b)** El profe escribe el número: −27. Copia: «(−9) · 3 = −27».",
              "**c)** Con la calculadora: 36 : 4 = 9. Copia: «(−36) : 4 = −9»."],
          s: ["**a)** Caja ROJA.", "**b)** Copia correcta.", "**c)** Copia correcta."],
          ad: "Manipulativo + calculadora: el alumno no ejecuta el cálculo, representa la cuenta y copia el resultado verificado." },
      ],
    },
    {
      t: "Regla de signos del juego", d: "Partida con dos cartas: producto como tirada.", ic: "dados",
      nv: [
        { in: "Baraja: 10 cartas (5 verdes +, 5 rojas −) de valores 2-3-4-5-6. Tirada = producto.",
          p: ["**a)** Sacas −6 y +2: ¿puntos?", "**b)** ¿Qué tirada de dos cartas da el mayor producto posible? ¿Y el menor?", "**c)** Con tres cartas −2, −3, −4: producto. ¿La regla par/impar se cumple? Escríbela con tu tirada."],
          s: ["**a)** −12.", "**b)** Mayor: (−6)(−5) = +30 · menor: (−6)(+5) = −30.", "**c)** −24: impar → negativo. La regla se cumple."] },
        { p: ["**a)** Tirada (−6)·(+2): ¿roja o verde? ¿Cuánto?", "**b)** ¿−4·−4 sale rojo o verde? ¿Cuánto?"],
          s: ["**a)** Roja −12.", "**b)** Verde +16."],
          ad: "El color del resultado se decide ANTES del número: dos tiradas, sin máximo/mínimo." },
        { p: ["**a)** Saca dos cartas (una verde, una roja). ¿El producto será + o −? Rodea. Calcula.", "**b)** Comprueba en la tabla de signos."],
          s: ["**a)** − · valor según las cartas.", "**b)** Coincide."],
          ad: "Predecir el signo primero (rodeo) y comprobar después." },
        { p: ["**a)** Tira la carta verde y la roja: ponlas sobre la mesa. El profe dice el signo del resultado.", "**b)** Copia: «verde × rojo = rojo = negativo»."],
          s: ["**b)** Copia correcta."],
          ad: "La tirada es física; la ley solo se copia." },
      ],
    },
  ],
};
